use_frameworks!

platform :ios, '9.0'

target 'SawoFramework_Example' do
  pod 'SawoFramework', :path => '../'
  pod 'SwiftKeychainWrapper'
  target 'SawoFramework_Tests' do
    inherit! :search_paths

    
  end
end
